spring.application.name=planner-backend
spring.datasource.url=jdbc:mysql://localhost:3306/smart_assignment_planner
spring.datasource.username=sap_user
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true